### ISSUE TITLE
GPU not detected

### ISSUE THREAD

**Issue by Kanss-code** [FunAudioLLM/InspireMusic#42]
When am trying to run gradio app.py it reverts back to CPU even when am using L40.
Somehow your script is not recognising GPU

```
python -c "import torch; print(torch.__version__)"
2.2.0+cu118
```

```
python -c "import torch; print(torch.cuda.is_available())"
True
```

**Comment by Kanss-code** [comment]
And due to this revert back flash attention fails to intialize
Same issue has been posted here: https://github.com/FunAudioLLM/InspireMusic/issues/30

**Comment by iris2c** [comment]
Thank you for your comments. You may change inspiremusic/transformer/qwen_encoder.py QwenEmbeddingEncoder class into :
`self.model = Qwen2ForCausalLM.from_pretrained(pretrain_path, device_map="cpu")`

**Comment by Kanss-code** [comment]
Now getting this error
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

**Comment by iris2c** [comment]
Note: If you're running this on Hugging Face Spaces, please set device_map="cpu" due to limited GPU availability.
If you're running the code locally with a GPU, you can keep the original setting device_map="auto".
To use FlashAttention, make sure it's installed first. Our latest environment supports flash-attn==2.7.4.post1.

**Comment by Kanss-code** [comment]
But when am activating conda env python 3.8 the latest flash attention shows a error stating : 
`ERROR: Package 'flash-attn' requires a different Python: 3.8.20 not in '>=3.9'`

**Comment by GiambaDS86** [comment]
> Thank you for your comments. You may change inspiremusic/transformer/qwen_encoder.py QwenEmbeddingEncoder class into : `self.model = Qwen2ForCausalLM.from_pretrained(pretrain_path, device_map="cpu")`

Even with this and multiple other fixes to run model explicitily on CPU (albeit my CUDA is detected by my env..) the generation breaks.

**Comment by Fluchw** [comment]
Oh, why am I doing the same on my 4090? It's so strange

**Comment by Fluchw** [comment]
> Oh, why am I doing the same on my 4090? It's so strange哦，为什么我的 4090 也出现同样的情况？太奇怪了


I've solved it, just change the 
```python
model=InspireMusicModel (model_2="InspireMusic-1.5B-Long") 
```
to
```python
model = InspireMusicModel(model_name = "InspireMusic-1.5B-Long",gpu=0)
```
